import type {
  Project,
  Client,
  TeamMember,
  Shoot,
  PlaybookPage,
  GearItem,
  GearKit,
  Asset,
  ChecklistStage,
  ChecklistItem,
  Task,
  ChecklistTemplates,
  PalType,
  ContentPiece,
  ContentPlatform,
  TrackedKpi,
} from "./types";
import { PLAYBOOK } from "./playbooksSeed";

const uid = (p: string) => `${p}_${Math.random().toString(36).slice(2, 9)}`;

const TEAM: TeamMember[] = [
  {
    id: "u_jevoy",
    name: "Jevoy Palmer",
    role: "owner",
    initials: "JP",
    color: "oklch(0.70 0.16 55)",
    capacity: 40,
    rate: 150,
  },
  {
    id: "u_adrienne",
    name: "Adrienne Palmer",
    role: "cfo",
    initials: "AP",
    color: "oklch(0.62 0.15 158)",
    capacity: 30,
    rate: 120,
  },
  {
    id: "u_shannen",
    name: "Shannen Murray",
    role: "pa",
    initials: "SM",
    color: "oklch(0.58 0.17 235)",
    capacity: 40,
    rate: 45,
  },
];

const CLIENTS: Client[] = [
  {
    id: "c_northwind",
    name: "Sarah Chen",
    company: "Northwind Labs",
    email: "sarah@northwind.co",
    phone: "(415) 555-0142",
    honeybookLink: "https://honeybook.com/p/northwind",
  },
  {
    id: "c_helix",
    name: "Theo Park",
    company: "Helix Robotics",
    email: "theo@helix.ai",
    phone: "(415) 555-0188",
  },
  { id: "c_atrium", name: "Maya Owens", company: "Atrium Partners", email: "maya@atrium.vc" },
  { id: "c_lumen", name: "Drew Holland", company: "Lumen Health", email: "drew@lumen.health" },
  { id: "c_beacon", name: "Priya Shah", company: "Beacon Co.", email: "priya@beacon.co" },
  { id: "c_vanta", name: "Idris Rahimi", company: "Vanta Group", email: "idris@vanta.group" },
  { id: "c_internal", name: "Palmer House", company: "Internal", email: "team@palmerhouse.co" },
];

const universalPre = [
  "project goal confirmed",
  "audience confirmed",
  "platform / use case confirmed",
  "deliverables confirmed",
  "script or outline confirmed",
  "interview questions drafted",
  "location confirmed",
  "shoot date confirmed",
  "client prep sent",
  "wardrobe guidance sent",
  "props / visual needs listed",
  "gear pull list created",
  "call sheet / shoot brief created",
  "Google Drive folder created",
];
const universalShoot = [
  "arrive on time",
  "confirm client goals",
  "confirm schedule",
  "15-minute setup complete",
  "camera settings checked",
  "audio test complete",
  "lighting checked",
  "background checked",
  "client comfort / warmup",
  "A-roll captured",
  "B-roll captured",
  "thumbnail / photo captured if needed",
  "backup card / file check",
  "wrap checklist complete",
  "next steps explained to client",
];
const universalPost = [
  "footage backed up",
  "footage organized",
  "selects pulled",
  "rough cut started",
  "internal review complete",
  "sound cleaned",
  "color adjusted",
  "graphics / motion added",
  "captions added",
  "review export created",
  "client review link sent",
  "revisions logged",
  "final export created",
];
const universalDelivery = [
  "final files exported",
  "filenames checked",
  "final files uploaded",
  "client notified",
  "usage notes sent",
  "social clips delivered",
  "archive folder updated",
  "testimonial requested",
  "follow-up offer suggested",
  "project marked delivered",
  "project moved to archive",
];

// Per-Pal additions on top of the universal lists (MD: 16 templates = 4 Pals × 4 stages)
const palPre: Record<PalType, string[]> = {
  Visibility: ["hook angles drafted (3+)", "vertical framing confirmed", "captions plan confirmed"],
  Systems: ["SOP outline reviewed", "screen recordings list built", "voiceover script confirmed"],
  YouTube: ["thumbnail concepts drafted", "title A/B drafted", "chapter map drafted"],
  Commercial: [
    "mood board approved",
    "shot list locked",
    "brand assets received",
    "talent confirmed",
  ],
};
const palShoot: Record<PalType, string[]> = {
  Visibility: ["short-form vertical batch shot", "trending sound options noted"],
  Systems: ["screen capture pass complete", "narrator pickup lines recorded"],
  YouTube: ["intro takes recorded", "cutaway B-roll captured", "thumbnail still captured"],
  Commercial: ["hero shot locked", "client sign-off on monitor", "alternate framings captured"],
};
const palPost: Record<PalType, string[]> = {
  Visibility: ["3 vertical cuts exported", "hook tested on mute"],
  Systems: ["chapter markers added", "voiceover mixed under -6dB"],
  YouTube: ["thumbnail finalized", "end-screen added", "SEO description written"],
  Commercial: ["color grade approved", "brand QC pass complete", "music license confirmed"],
};
const palDelivery: Record<PalType, string[]> = {
  Visibility: ["captions burned in", "delivered in 9:16 + 1:1"],
  Systems: ["SOP doc linked alongside video", "loom alternative uploaded"],
  YouTube: ["video scheduled", "community post drafted"],
  Commercial: ["broadcast-spec master delivered", "press kit assembled"],
};

export const DEFAULT_TEMPLATES: ChecklistTemplates = {
  Visibility: {
    "Pre-Production": [...universalPre, ...palPre.Visibility],
    "Shoot Day": [...universalShoot, ...palShoot.Visibility],
    "Post-Production": [...universalPost, ...palPost.Visibility],
    Delivery: [...universalDelivery, ...palDelivery.Visibility],
  },
  Systems: {
    "Pre-Production": [...universalPre, ...palPre.Systems],
    "Shoot Day": [...universalShoot, ...palShoot.Systems],
    "Post-Production": [...universalPost, ...palPost.Systems],
    Delivery: [...universalDelivery, ...palDelivery.Systems],
  },
  YouTube: {
    "Pre-Production": [...universalPre, ...palPre.YouTube],
    "Shoot Day": [...universalShoot, ...palShoot.YouTube],
    "Post-Production": [...universalPost, ...palPost.YouTube],
    Delivery: [...universalDelivery, ...palDelivery.YouTube],
  },
  Commercial: {
    "Pre-Production": [...universalPre, ...palPre.Commercial],
    "Shoot Day": [...universalShoot, ...palShoot.Commercial],
    "Post-Production": [...universalPost, ...palPost.Commercial],
    Delivery: [...universalDelivery, ...palDelivery.Commercial],
  },
};

export function buildChecklistsFromTemplate(
  templates: ChecklistTemplates,
  palType: PalType,
  done: Partial<Record<ChecklistStage, number>> = {},
): Record<ChecklistStage, ChecklistItem[]> {
  const t = templates[palType] ?? DEFAULT_TEMPLATES[palType];
  const mk = (arr: string[], n = 0): ChecklistItem[] =>
    arr.map((text, i) => ({ id: uid("ci"), text, done: i < n }));
  return {
    "Pre-Production": mk(t["Pre-Production"], done["Pre-Production"]),
    "Shoot Day": mk(t["Shoot Day"], done["Shoot Day"]),
    "Post-Production": mk(t["Post-Production"], done["Post-Production"]),
    Delivery: mk(t["Delivery"], done["Delivery"]),
  };
}

// Legacy helper kept for existing seed call sites — uses Commercial template
export function buildChecklists(
  donePre = 0,
  doneShoot = 0,
  donePost = 0,
  doneDel = 0,
): Record<ChecklistStage, ChecklistItem[]> {
  return buildChecklistsFromTemplate(DEFAULT_TEMPLATES, "Commercial", {
    "Pre-Production": donePre,
    "Shoot Day": doneShoot,
    "Post-Production": donePost,
    Delivery: doneDel,
  });
}

const today = new Date();
const iso = (offset: number) => new Date(today.getTime() + offset * 86400000).toISOString();

const PROJECTS: Project[] = [
  {
    id: "p_001",
    title: "Founder Story · Pt. 2",
    clientId: "c_northwind",
    internal: false,
    palType: "Commercial",
    stage: "In Post",
    ownerId: "u_jevoy",
    shootDate: iso(-7),
    deliveryDate: iso(4),
    quoted: 18500,
    cost: 6200,
    driveLink: "https://drive.google.com/d/northwind-pt2",
    honeybookLink: "https://honeybook.com/p/northwind",
    priority: "High",
    checklists: buildChecklists(13, 13, 8, 0),
    log: [
      {
        id: uid("lg"),
        ts: iso(-1),
        who: "Jevoy Palmer",
        type: "production",
        text: "Cut v3 uploaded for internal review.",
      },
    ],
    createdAt: iso(-30),
  },
  {
    id: "p_002",
    title: "Q2 Product Launch Reel",
    clientId: "c_helix",
    internal: false,
    palType: "Commercial",
    stage: "Shoot Day",
    ownerId: "u_jevoy",
    shootDate: iso(3),
    deliveryDate: iso(18),
    quoted: 32000,
    cost: 9100,
    priority: "High",
    checklists: buildChecklists(11, 5, 0, 0),
    log: [
      {
        id: uid("lg"),
        ts: iso(-2),
        who: "Jevoy Palmer",
        type: "client",
        text: "Shot list approved by Theo.",
      },
    ],
    createdAt: iso(-21),
  },
  {
    id: "p_003",
    title: "CEO Interview Series",
    clientId: "c_atrium",
    internal: false,
    palType: "YouTube",
    stage: "Pre-Production",
    ownerId: "u_shannen",
    shootDate: iso(14),
    deliveryDate: iso(35),
    quoted: 12000,
    priority: "Med",
    checklists: buildChecklists(6, 0, 0, 0),
    log: [],
    createdAt: iso(-10),
  },
  {
    id: "p_004",
    title: "Podcast — Ep. 14 → 17",
    clientId: "c_internal",
    internal: true,
    palType: "YouTube",
    stage: "In Post",
    ownerId: "u_jevoy",
    shootDate: iso(-14),
    deliveryDate: iso(10),
    quoted: 0,
    priority: "Med",
    checklists: buildChecklists(13, 13, 10, 0),
    log: [],
    createdAt: iso(-45),
  },
  {
    id: "p_005",
    title: "Recruiting Sizzle",
    clientId: "c_lumen",
    internal: false,
    palType: "Visibility",
    stage: "In Post",
    ownerId: "u_jevoy",
    shootDate: iso(-5),
    deliveryDate: iso(1),
    quoted: 7500,
    cost: 2200,
    priority: "High",
    checklists: buildChecklists(13, 13, 12, 0),
    log: [],
    createdAt: iso(-20),
  },
  {
    id: "p_006",
    title: "Training Module 03–05",
    clientId: "c_beacon",
    internal: false,
    palType: "Systems",
    stage: "Delivered",
    ownerId: "u_adrienne",
    shootDate: iso(-25),
    deliveryDate: iso(-2),
    quoted: 14400,
    cost: 4800,
    priority: "Low",
    clientRating: 5,
    checklists: buildChecklists(13, 13, 13, 10),
    log: [],
    createdAt: iso(-60),
  },
  {
    id: "p_007",
    title: "Conference Recap",
    clientId: "c_vanta",
    internal: false,
    palType: "Commercial",
    stage: "Shoot Day",
    ownerId: "u_jevoy",
    shootDate: iso(5),
    deliveryDate: iso(20),
    quoted: 21000,
    priority: "Med",
    checklists: buildChecklists(9, 0, 0, 0),
    log: [],
    createdAt: iso(-12),
  },
  {
    id: "p_008",
    title: "Inbound Lead Magnet Reels",
    clientId: "c_internal",
    internal: true,
    palType: "Visibility",
    stage: "Booked",
    ownerId: "u_shannen",
    shootDate: iso(8),
    deliveryDate: iso(22),
    priority: "Low",
    checklists: buildChecklists(3, 0, 0, 0),
    log: [],
    createdAt: iso(-4),
  },
  {
    id: "p_009",
    title: "Brand Refresh Walkthrough",
    clientId: "c_northwind",
    internal: false,
    palType: "Systems",
    stage: "Proposal Sent",
    ownerId: "u_jevoy",
    quoted: 9800,
    priority: "Med",
    checklists: buildChecklists(),
    log: [],
    createdAt: iso(-2),
  },
  {
    id: "p_010",
    title: "Customer Story · Vol. 1",
    clientId: "c_helix",
    internal: false,
    palType: "Commercial",
    stage: "Lead",
    ownerId: "u_jevoy",
    priority: "Low",
    checklists: buildChecklists(),
    log: [],
    createdAt: iso(-1),
  },
];

const SHOOTS: Shoot[] = [
  {
    id: "s_01",
    projectId: "p_005",
    date: iso(1),
    location: "Edit Bay 1",
    arrival: "09:30",
    goals: "Final cut review",
    crewIds: ["u_jevoy"],
    status: "Scheduled",
  },
  {
    id: "s_02",
    projectId: "p_002",
    date: iso(3),
    location: "Helix HQ — Bay 4",
    arrival: "07:30",
    startTime: "08:00",
    endTime: "18:00",
    goals: "Main launch reel; 6 setups",
    crewIds: ["u_jevoy", "u_jevoy", "u_shannen"],
    status: "Scheduled",
  },
  {
    id: "s_03",
    projectId: "p_001",
    date: iso(4),
    location: "Edit Bay 2",
    goals: "Color + sound lock",
    crewIds: ["u_jevoy"],
    status: "Scheduled",
  },
  {
    id: "s_04",
    projectId: "p_007",
    date: iso(5),
    location: "Pier 27 — Main Hall",
    arrival: "06:30",
    startTime: "07:30",
    endTime: "20:00",
    goals: "Conference floor + speaker B-roll",
    crewIds: ["u_jevoy", "u_shannen"],
    status: "Scheduled",
  },
  {
    id: "s_05",
    projectId: "p_008",
    date: iso(8),
    location: "Palmer House Studio",
    arrival: "09:00",
    startTime: "09:30",
    endTime: "13:00",
    goals: "Batch 4 reels",
    crewIds: ["u_jevoy", "u_shannen"],
    status: "Scheduled",
  },
  {
    id: "s_06",
    projectId: "p_003",
    date: iso(14),
    location: "Atrium HQ — Boardroom",
    arrival: "08:00",
    startTime: "08:30",
    endTime: "14:00",
    goals: "3-camera interview",
    crewIds: ["u_jevoy", "u_jevoy", "u_shannen"],
    status: "Scheduled",
  },
  {
    id: "s_07",
    projectId: "p_001",
    date: iso(-7),
    location: "Northwind Office",
    crewIds: ["u_jevoy", "u_jevoy"],
    status: "Complete",
  },
];

const GEAR_ITEMS: GearItem[] = [
  {
    id: "g_01",
    name: "Sony FX3 (A-cam)",
    category: "Camera",
    status: "Available",
    kitIds: ["k_solo", "k_podcast", "k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1589872307379-0ffdf9829123?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_02",
    name: "Sony FX3 (B-cam)",
    category: "Camera",
    status: "On Shoot",
    kitIds: ["k_podcast"],
    imageUrl:
      "https://images.unsplash.com/photo-1581591524425-c7e0978865fc?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_03",
    name: "Sony 24-70 GM II",
    category: "Lens",
    status: "Available",
    kitIds: ["k_solo", "k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1617005082133-548c4dd27f35?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_04",
    name: "Sigma 35mm f/1.4",
    category: "Lens",
    status: "Available",
    kitIds: ["k_solo"],
    imageUrl:
      "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_05",
    name: "Sennheiser MKE 600",
    category: "Audio",
    status: "Available",
    kitIds: ["k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_06",
    name: "DJI Mic 2 (4-pack)",
    category: "Audio",
    status: "Available",
    kitIds: ["k_solo", "k_podcast", "k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_07",
    name: "Aputure 600D Pro",
    category: "Lighting",
    status: "Available",
    kitIds: ["k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_08",
    name: "Aputure 300X (x2)",
    category: "Lighting",
    status: "Repair",
    kitIds: ["k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_09",
    name: "Manfrotto 504X Tripod",
    category: "Support",
    status: "Available",
    kitIds: ["k_solo", "k_podcast"],
    imageUrl:
      "https://images.unsplash.com/photo-1473893604213-3df9c15cf045?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_10",
    name: "Rode Caster Pro II",
    category: "Audio",
    status: "Available",
    kitIds: ["k_podcast"],
    imageUrl:
      "https://images.unsplash.com/photo-1485579149621-3123dd979885?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_11",
    name: "Atomos Ninja V",
    category: "Monitor",
    status: "Available",
    kitIds: ["k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=800&q=70",
  },
  {
    id: "g_12",
    name: "SanDisk CFexpress (x6)",
    category: "Media",
    status: "Available",
    kitIds: ["k_solo", "k_podcast", "k_training"],
    imageUrl:
      "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=70",
  },
];

const GEAR_KITS: GearKit[] = [
  {
    id: "k_solo",
    name: "Solo Interview Kit",
    itemIds: ["g_01", "g_03", "g_06", "g_09", "g_12"],
    useCase: "Interviews & talking-head shoots",
  },
  {
    id: "k_podcast",
    name: "Podcast Kit",
    itemIds: ["g_01", "g_02", "g_06", "g_09", "g_10", "g_12"],
    useCase: "Multi-mic podcast sessions",
  },
  {
    id: "k_training",
    name: "Client Training Kit",
    itemIds: ["g_01", "g_03", "g_05", "g_07", "g_08", "g_11", "g_12"],
    useCase: "On-location training videos",
  },
  {
    id: "k_social",
    name: "Social Content Kit",
    itemIds: ["g_01", "g_04", "g_06", "g_12"],
    useCase: "Reels & short-form capture",
  },
];

const ASSETS: Asset[] = [
  {
    id: "a_01",
    projectId: "p_001",
    name: "Founder Story · Cut v3",
    type: "Review",
    status: "Review",
    sizeGb: 4.2,
    link: "https://frame.io/n-pt2-v3",
    updatedAt: iso(-1),
  },
  {
    id: "a_02",
    projectId: "p_001",
    name: "Raw footage day 1",
    type: "Footage",
    status: "Approved",
    sizeGb: 320,
    link: "https://drive.google.com/d/northwind-d1",
    updatedAt: iso(-7),
  },
  {
    id: "a_03",
    projectId: "p_005",
    name: "Lumen Sizzle · Cut v2",
    type: "Review",
    status: "Review",
    sizeGb: 1.4,
    link: "https://frame.io/lumen-v2",
    updatedAt: iso(-1),
  },
  {
    id: "a_04",
    projectId: "p_006",
    name: "Beacon Module 03 FINAL",
    type: "Final",
    status: "Delivered",
    sizeGb: 2.8,
    link: "https://drive.google.com/d/beacon-03",
    updatedAt: iso(-2),
  },
  {
    id: "a_05",
    projectId: "p_004",
    name: "Podcast Ep14 master",
    type: "Audio",
    status: "Approved",
    sizeGb: 0.6,
    updatedAt: iso(-10),
  },
  {
    id: "a_06",
    projectId: "p_003",
    name: "Atrium intro motion",
    type: "Graphics",
    status: "Draft",
    sizeGb: 0.2,
    updatedAt: iso(-3),
  },
  {
    id: "a_07",
    projectId: "p_002",
    name: "Helix shot list — v4",
    type: "Stills",
    status: "Approved",
    sizeGb: 0.05,
    updatedAt: iso(-2),
  },
];

const mkClip = (label: string, platform: ContentPlatform) => ({
  id: uid("clip"),
  label,
  platform,
  done: false,
});

const CONTENT_PIECES: ContentPiece[] = [
  {
    id: "cp_01",
    title: "Why You Look Fake on Camera (It's Not What You Think)",
    hypothesis:
      "The reason most business videos feel fake isn't the script — it's that the camera creates a performance mode that kills authenticity. And there's a specific technique to break through it.",
    palLane: "Spotlight",
    format: "Investigation + Personal Experiment (Veritasium × Mark Rober)",
    stage: "Scripted",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram", "LinkedIn"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
    ],
    repurposableClips: [
      mkClip("Side-by-side footage comparison (30 sec)", "Instagram"),
      mkClip("'The camera doesn't capture who you are — it captures who you think you should be' (15 sec)", "Instagram"),
      mkClip("The reveal of the hidden camera technique (45 sec)", "YouTube"),
      mkClip("Trust data reveal — 61% chose Method 3 (30 sec)", "LinkedIn"),
    ],
    thumbnailConcept:
      "Split-screen — stiff business owner on left (red tint) vs. same person laughing naturally (golden tint). Jevoy in center pointing at the contrast.",
    faithThread:
      "There's a verse in Genesis about humans being made in the image of God. My job isn't to create an image of them. It's to reveal the one that's already there.",
    createdAt: iso(-14),
  },
  {
    id: "cp_02",
    title: "The Most Profitable Business Video No One Talks About",
    hypothesis:
      "The most valuable business videos aren't the ones that go viral — they're the ones that replace a conversation the business owner was having 50 times a month.",
    palLane: "Evergreen",
    format: "Case Study Narrative (Johnny Harris × Jay Shetty)",
    stage: "Concept",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram", "LinkedIn"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
    ],
    repurposableClips: [
      mkClip("'The most profitable video is the one that replaces a conversation' (20 sec)", "Instagram"),
      mkClip("The $2K video → $200K math breakdown (30 sec)", "LinkedIn"),
      mkClip("Client reaction when they see their sales cycle data (45 sec)", "YouTube"),
    ],
    thumbnailConcept:
      "A calculator showing '$200,000' next to a simple video thumbnail on a laptop. Jevoy looking genuinely surprised.",
    faithThread:
      "Stewardship isn't just about money. It's about time. If you're having the same conversation 50 times a month, you're not stewarding your expertise — you're hoarding it.",
    createdAt: iso(-12),
  },
  {
    id: "cp_03",
    title: "I Watched 100 Business Videos So You Don't Have To",
    hypothesis:
      "There's a pattern to why business videos fail, and it has nothing to do with production quality. It's a storytelling problem disguised as a budget problem.",
    palLane: "Evergreen",
    format: "Investigation + Data Visualization (Veritasium × Johnny Harris)",
    stage: "In Edit",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram", "LinkedIn"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
    ],
    repurposableClips: [
      mkClip("The 2×2 matrix reveal with the surprising data (30 sec)", "Instagram"),
      mkClip("'Three storytelling mistakes every business video makes' rapid breakdown (45 sec)", "Instagram"),
      mkClip("The bakery video case study — why it works (60 sec)", "YouTube"),
      mkClip("'Story > Production' LinkedIn article excerpt", "LinkedIn"),
    ],
    thumbnailConcept:
      "Jevoy sitting in front of a wall of 100 video thumbnails, circling three with a red marker. Expression: focused, slightly amused.",
    faithThread:
      "There's a reason parables have lasted 2,000 years and PowerPoints haven't. Story is how humans were designed to learn.",
    notes: "Script complete. B-roll footage needs to be sourced (100 business video examples). Edit starts this week.",
    createdAt: iso(-20),
  },
  {
    id: "cp_04",
    title: "What Happens When You Film a Business Owner for 8 Hours",
    hypothesis:
      "The best content a business owner will ever create is already inside them — it just takes the right process to pull it out.",
    palLane: "Spotlight",
    format: "Build in Public Documentary (Mark Rober × Matt Gray)",
    stage: "Concept",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
    ],
    repurposableClips: [
      mkClip("The moment the client stops performing and starts being real (30 sec)", "Instagram"),
      mkClip("Before/after: Hour 1 vs. Hour 7 (20 sec)", "Instagram"),
      mkClip("Jevoy explaining interview technique that breaks camera anxiety (45 sec)", "YouTube"),
      mkClip("Client's reaction to the final edit (30 sec)", "Instagram"),
    ],
    thumbnailConcept:
      "Two frames side by side — nervous client at 'HOUR 1' vs. animated, laughing client at 'HOUR 7'.",
    faithThread:
      "I believe every person has a story worth telling. Not because it'll go viral — because it's true. And truth has a way of resonating.",
    createdAt: iso(-10),
  },
  {
    id: "cp_05",
    title: "The Algorithm Doesn't Care About Your Brand",
    hypothesis:
      "Business owners obsess over brand consistency in their videos, but the algorithm rewards something completely different — and understanding that gap is the key to video that actually gets seen.",
    palLane: "Reel",
    format: "Misconception Buster (Veritasium)",
    stage: "Concept",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram", "LinkedIn"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
    ],
    repurposableClips: [
      mkClip("'The algorithm doesn't reward consistency. It rewards curiosity.' (15 sec)", "Instagram"),
      mkClip("Branded vs. story-driven video performance comparison (30 sec)", "LinkedIn"),
      mkClip("Business owner's reaction when ugly video outperforms polished one (30 sec)", "Instagram"),
    ],
    thumbnailConcept:
      "Polished corporate thumbnail with big red 'X' vs. rough authentic thumbnail with '15K views' overlay and green checkmark.",
    faithThread:
      "There's something freeing about letting go of the image you think you need to project and just... being honest. That's true in business. That's true in life.",
    createdAt: iso(-8),
  },
  {
    id: "cp_06",
    title: "Every Business Has a $1 Million Video Inside It",
    hypothesis:
      "Inside every business is one video that, if made correctly, would fundamentally change their trajectory. Most businesses never make it because they're focused on the wrong kind of video.",
    palLane: "System",
    format: "Wisdom Reframe + Framework (Jay Shetty × Matt Gray)",
    stage: "Scripted",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram", "LinkedIn", "Facebook"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
      { platform: "Facebook", status: "pending" },
    ],
    repurposableClips: [
      mkClip("'Every business has a million-dollar video inside it. Most never make it.' (15 sec)", "Instagram"),
      mkClip("The three-question Keystone Video framework (45 sec)", "LinkedIn"),
      mkClip("The contractor example — Keystone Video results (60 sec)", "YouTube"),
      mkClip("The $2,500 → $1.5M math breakdown (30 sec)", "Facebook"),
    ],
    thumbnailConcept:
      "Jevoy holding up one finger with a golden glow effect. Text: '$1M VIDEO'. Background: blurred footage of diverse businesses.",
    faithThread:
      "The parable of the talents isn't just about money. It's about what you do with what you've been given. Your expertise is a gift. Video is how you multiply it.",
    createdAt: iso(-6),
  },
  {
    id: "cp_07",
    title: "I Gave 5 Businesses the Same Camera. Here's What Happened.",
    hypothesis:
      "The gap between amateur and professional business video isn't equipment — it's thinking. And that gap can be closed with one strategic conversation before anyone touches a camera.",
    palLane: "Evergreen",
    format: "Experiment (Mark Rober)",
    stage: "Concept",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram", "LinkedIn"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
    ],
    repurposableClips: [
      mkClip("Side-by-side: worst and best video from the same camera (30 sec)", "Instagram"),
      mkClip("'Equipment is the last 10%. Strategy is the first 90%.' (15 sec)", "Instagram"),
      mkClip("Before/after of re-shot video with strategy (45 sec)", "YouTube"),
    ],
    thumbnailConcept:
      "Five video frames in a row — four with red 'X' marks, one with a gold star. All shot on the same camera. Jevoy in the corner looking analytical.",
    faithThread:
      "Tools don't create value. People do. A camera in the wrong hands is just expensive plastic. In the right hands — with the right story — it's a bridge between what you know and who needs to hear it.",
    createdAt: iso(-5),
  },
  {
    id: "cp_08",
    title: "Why Your Competitor's Terrible Video Is Beating Yours",
    hypothesis:
      "In the business video space, 'good enough and published' consistently outperforms 'perfect and in progress.' But the nuance is about redefining what 'good' means — not lowering your standards.",
    palLane: "Reel",
    format: "Misconception Buster + Case Study (Veritasium × Johnny Harris)",
    stage: "Concept",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram", "LinkedIn"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
    ],
    repurposableClips: [
      mkClip("'Perfectionism isn't a quality standard. It's a fear response.' (15 sec)", "Instagram"),
      mkClip("The math: 8 months published vs. 8 months in revisions (30 sec)", "LinkedIn"),
      mkClip("Strategic Minimum Viable Video framework by industry (45 sec)", "YouTube"),
    ],
    thumbnailConcept:
      "Split screen — beautiful video with '0 LEADS' vs. amateur video with '47 LEADS/MONTH'. Jevoy in the middle with a 'what?!' expression.",
    faithThread:
      "There's a difference between excellence and perfectionism. Excellence serves others. Perfectionism serves your ego. I'm learning that in real time with this channel.",
    createdAt: iso(-4),
  },
  {
    id: "cp_09",
    title: "The Video That Replaced a $120K Employee",
    hypothesis:
      "The most underrated use of business video isn't marketing — it's internal operations. A single well-made training video can replace the most expensive, repetitive part of any business.",
    palLane: "System",
    format: "Case Study + Build in Public (Johnny Harris × Mark Rober)",
    stage: "Concept",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "LinkedIn", "Facebook"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "LinkedIn", status: "pending" },
      { platform: "Facebook", status: "pending" },
    ],
    repurposableClips: [
      mkClip("The $120K math breakdown (20 sec)", "LinkedIn"),
      mkClip("'The most expensive thing in your business is explaining the same thing twice' (15 sec)", "Instagram"),
      mkClip("Employee reaction when they stop being the 'explainer' (30 sec)", "YouTube"),
      mkClip("Quick tour of the finished 15-video library (45 sec)", "YouTube"),
    ],
    thumbnailConcept:
      "Stack of money ($120K in bold) next to a laptop showing a clean video library interface. Jevoy pointing at the laptop with a 'this is it' expression.",
    faithThread:
      "Stewardship means using what you have wisely. If your best people are spending their days repeating themselves instead of creating — that's not stewardship. That's waste.",
    createdAt: iso(-3),
  },
  {
    id: "cp_10",
    title: "I Built a Video Strategy for a Business I Know Nothing About",
    hypothesis:
      "A good video strategist doesn't need to be an expert in your industry. They need to be an expert in asking the right questions. The strategy process itself is the proof.",
    palLane: "Spotlight",
    format: "Live Experiment + Build in Public (Mark Rober × Matt Gray)",
    stage: "Concept",
    primaryPlatform: "YouTube",
    targetPlatforms: ["YouTube", "Instagram"],
    platforms: [
      { platform: "YouTube", status: "pending" },
      { platform: "Instagram", status: "pending" },
    ],
    repurposableClips: [
      mkClip("Discovery call moment — Jevoy identifies the real story (30 sec)", "Instagram"),
      mkClip("'I don't need to know your industry. I need to know your customer's biggest question.' (15 sec)", "Instagram"),
      mkClip("Business owner's reaction to completed strategy (30 sec)", "YouTube"),
      mkClip("Whiteboard strategy sketch — time-lapse (20 sec)", "Instagram"),
    ],
    thumbnailConcept:
      "Jevoy sitting across from a business owner in an unexpected setting (woodworking shop / marine lab), both looking at a whiteboard with a video strategy sketched out.",
    faithThread:
      "Every person's work has dignity. Whether you're building furniture or building software, there's a story in what you do that deserves to be told well.",
    createdAt: iso(-1),
  },
];

const TRACKED_KPIS: TrackedKpi[] = [
  // Jevoy KPIs
  {
    id: uid("kpi"),
    name: "Inquiry to Call Booking",
    owner: "owner",
    category: "Sales",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 4,
    ratioDenominator: 5,
    ratioNumeratorLabel: "calls booked",
    ratioDenominatorLabel: "inquiries",
    frequency: "Weekly",
    whyItMatters: "Are leads getting handled and moving to calls?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Call to Proposal",
    owner: "owner",
    category: "Sales",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 3,
    ratioDenominator: 4,
    ratioNumeratorLabel: "proposals sent",
    ratioDenominatorLabel: "calls attended",
    frequency: "Weekly",
    whyItMatters: "Are calls turning into real opportunities?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Proposal Close Rate",
    owner: "owner",
    category: "Sales",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 2,
    ratioDenominator: 3,
    ratioNumeratorLabel: "booked",
    ratioDenominatorLabel: "proposals",
    frequency: "Monthly",
    whyItMatters: "Is the offer clear and working?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Internal Systems Created",
    owner: "owner",
    category: "Systems",
    target: 2,
    actual: 1,
    unit: "systems",
    isLowerBetter: false,
    isRatio: false,
    ratioNumerator: 0,
    ratioDenominator: 0,
    ratioNumeratorLabel: "",
    ratioDenominatorLabel: "",
    frequency: "Weekly",
    whyItMatters: "Shows whether the business is becoming less dependent on memory.",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Problems Logged vs Solved",
    owner: "pa",
    category: "Systems",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 8,
    ratioDenominator: 10,
    ratioNumeratorLabel: "solved",
    ratioDenominatorLabel: "logged",
    frequency: "Monthly",
    whyItMatters: "Are we fixing the friction or just living with it?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Video Minutes Produced",
    owner: "pa",
    category: "Content",
    target: 120,
    actual: 45,
    unit: " mins",
    isLowerBetter: false,
    isRatio: false,
    ratioNumerator: 0,
    ratioDenominator: 0,
    ratioNumeratorLabel: "",
    ratioDenominatorLabel: "",
    frequency: "Monthly",
    whyItMatters: "Total volume of final output we put into the world.",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Posts Published",
    owner: "pa",
    category: "Content",
    target: 20,
    actual: 12,
    unit: " posts",
    isLowerBetter: false,
    isRatio: false,
    ratioNumerator: 0,
    ratioDenominator: 0,
    ratioNumeratorLabel: "",
    ratioDenominatorLabel: "",
    frequency: "Monthly",
    whyItMatters: "Consistency in our own marketing engine.",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  
  // Adrienne KPIs
  {
    id: uid("kpi"),
    name: "Deposit Collection",
    owner: "cfo",
    category: "Finance",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 2,
    ratioDenominator: 2,
    ratioNumeratorLabel: "deposits paid",
    ratioDenominatorLabel: "projects booked",
    frequency: "Weekly",
    whyItMatters: "Are booked clients actually committed?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Invoice Collection Rate",
    owner: "cfo",
    category: "Finance",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 8,
    ratioDenominator: 9,
    ratioNumeratorLabel: "paid",
    ratioDenominatorLabel: "sent",
    frequency: "Weekly",
    whyItMatters: "Shows real cash health and collection flow.",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Project Costs Logged",
    owner: "cfo",
    category: "Finance",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 4,
    ratioDenominator: 5,
    ratioNumeratorLabel: "costs logged",
    ratioDenominatorLabel: "completed projects",
    frequency: "Monthly",
    whyItMatters: "Can't calculate true margin if costs are missing.",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },

  // Shannen KPIs
  {
    id: uid("kpi"),
    name: "Client Prep Completion",
    owner: "pa",
    category: "Operations",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 3,
    ratioDenominator: 4,
    ratioNumeratorLabel: "prep completed",
    ratioDenominatorLabel: "prep sent",
    frequency: "Weekly",
    whyItMatters: "Are clients ready before shoot day?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Shoot Briefs Created",
    owner: "pa",
    category: "Production",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 4,
    ratioDenominator: 4,
    ratioNumeratorLabel: "briefs complete",
    ratioDenominatorLabel: "shoots scheduled",
    frequency: "Weekly",
    whyItMatters: "Reduces Jevoy-brain dependence on set.",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "48-Hour Readiness Rate",
    owner: "pa",
    category: "Production",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 2,
    ratioDenominator: 3,
    ratioNumeratorLabel: "ready",
    ratioDenominatorLabel: "upcoming shoots",
    frequency: "Weekly",
    whyItMatters: "Is production under control or improvising?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Review Return Rate",
    owner: "pa",
    category: "Client Experience",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 3,
    ratioDenominator: 5,
    ratioNumeratorLabel: "reviews returned",
    ratioDenominatorLabel: "links sent",
    frequency: "Weekly",
    whyItMatters: "Are clients giving feedback, or are projects stalled?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Testimonial Capture",
    owner: "pa",
    category: "Sales",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 1,
    ratioDenominator: 3,
    ratioNumeratorLabel: "received",
    ratioDenominatorLabel: "requested",
    frequency: "Monthly",
    whyItMatters: "Are we harvesting proof from happy clients?",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Review Sent / Completed",
    owner: "pa",
    category: "Production",
    target: 0,
    actual: 0,
    unit: "",
    isLowerBetter: false,
    isRatio: true,
    ratioNumerator: 0,
    ratioDenominator: 0,
    ratioNumeratorLabel: "reviews completed",
    ratioDenominatorLabel: "reviews sent",
    frequency: "Weekly",
    whyItMatters: "Tracks how many review links Shannen sends out and how many clients close them out — surfaces stalled deliveries.",
    notes: "Auto-counts from projects in the 'Review Sent' and 'Delivered' pipeline stages.",
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uid("kpi"),
    name: "Shoots Successfully Filmed",
    owner: "pa",
    category: "Production",
    target: 5,
    actual: 3,
    unit: " shoots",
    isLowerBetter: false,
    isRatio: false,
    ratioNumerator: 0,
    ratioDenominator: 0,
    ratioNumeratorLabel: "",
    ratioDenominatorLabel: "",
    frequency: "Monthly",
    whyItMatters: "Fun tracking for total production volume handled without major issues.",
    notes: "",
    active: true,
    createdAt: new Date().toISOString(),
  },
];

const TASKS: Task[] = [
  {
    id: uid("t"),
    title: "Send Northwind final cut for review",
    assigneeId: "u_jevoy",
    projectId: "p_001",
    dueDate: iso(2),
    status: "doing",
    priority: "High",
    createdAt: iso(-1),
  },
  {
    id: uid("t"),
    title: "Pull Helix shoot kit and label cases",
    assigneeId: "u_shannen",
    projectId: "p_002",
    dueDate: iso(2),
    status: "todo",
    priority: "High",
    createdAt: iso(-1),
  },
  {
    id: uid("t"),
    title: "Confirm Helix call sheet w/ Theo",
    assigneeId: "u_shannen",
    projectId: "p_002",
    dueDate: iso(1),
    status: "todo",
    priority: "High",
    createdAt: iso(-2),
  },
  {
    id: uid("t"),
    title: "Draft Atrium interview questions",
    assigneeId: "u_jevoy",
    projectId: "p_003",
    dueDate: iso(7),
    status: "todo",
    priority: "Med",
    createdAt: iso(-1),
  },
  {
    id: uid("t"),
    title: "Color pass — Lumen sizzle v3",
    assigneeId: "u_jevoy",
    projectId: "p_005",
    dueDate: iso(0),
    status: "doing",
    priority: "High",
    createdAt: iso(-2),
  },
  {
    id: uid("t"),
    title: "Send Beacon invoice (final 50%)",
    assigneeId: "u_adrienne",
    projectId: "p_006",
    dueDate: iso(1),
    status: "todo",
    priority: "Med",
    createdAt: iso(-1),
  },
  {
    id: uid("t"),
    title: "Scout Pier 27 for conference recap",
    assigneeId: "u_shannen",
    projectId: "p_007",
    dueDate: iso(3),
    status: "todo",
    priority: "Med",
    createdAt: iso(-3),
  },
  {
    id: uid("t"),
    title: "Batch shoot 4 reels (studio)",
    assigneeId: "u_shannen",
    projectId: "p_008",
    dueDate: iso(8),
    status: "todo",
    priority: "Low",
    createdAt: iso(-2),
  },
  {
    id: uid("t"),
    title: "Draft Northwind brand-refresh proposal",
    assigneeId: "u_jevoy",
    projectId: "p_009",
    dueDate: iso(2),
    status: "doing",
    priority: "Med",
    createdAt: iso(-1),
  },
  {
    id: uid("t"),
    title: "Reconcile Q1 contractor spend",
    assigneeId: "u_adrienne",
    dueDate: iso(-1),
    status: "done",
    priority: "Low",
    createdAt: iso(-7),
  },
  {
    id: uid("t"),
    title: "Archive Beacon project to long-term storage",
    assigneeId: "u_shannen",
    projectId: "p_006",
    status: "done",
    priority: "Low",
    createdAt: iso(-4),
  },
  {
    id: uid("t"),
    title: "Update Pals playbook page (Visibility)",
    assigneeId: "u_jevoy",
    status: "todo",
    priority: "Low",
    createdAt: iso(-1),
  },
];

export const SEED = {
  team: TEAM,
  clients: [] as Client[],
  projects: [] as Project[],
  shoots: [] as Shoot[],
  playbook: PLAYBOOK,
  gearItems: [] as GearItem[],
  gearKits: [] as GearKit[],
  assets: [] as Asset[],
  tasks: [] as Task[],
  templates: DEFAULT_TEMPLATES,
  contentPieces: [] as ContentPiece[],
  trackedKpis: [] as TrackedKpi[],
};

