/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProductionsRouteImport } from './routes/productions'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as GearRouteImport } from './routes/gear'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShootsIdRouteImport } from './routes/shoots.$id'
import { Route as ScriptsYourboyRouteImport } from './routes/scripts.yourboy'
import { Route as ScriptsStrategyRouteImport } from './routes/scripts.strategy'
import { Route as ScriptsResearchRouteImport } from './routes/scripts.research'
import { Route as ScriptsManualRouteImport } from './routes/scripts.manual'
import { Route as ScriptsNumRouteImport } from './routes/scripts.$num'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PlaybookSlugRouteImport } from './routes/playbook.$slug'
import { Route as KpisPaRouteImport } from './routes/kpis.pa'
import { Route as KpisOwnerRouteImport } from './routes/kpis.owner'
import { Route as KpisCfoRouteImport } from './routes/kpis.cfo'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as ApiStudioChatRouteImport } from './routes/api/studio-chat'
import { Route as ApiPalsRouteImport } from './routes/api/pals'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsRoute = ProductionsRouteImport.update({
  id: '/productions',
  path: '/productions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootsIdRoute = ShootsIdRouteImport.update({
  id: '/shoots/$id',
  path: '/shoots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsYourboyRoute = ScriptsYourboyRouteImport.update({
  id: '/yourboy',
  path: '/yourboy',
  getParentRoute: () => ScriptsRoute,
} as any)
const ScriptsStrategyRoute = ScriptsStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => ScriptsRoute,
} as any)
const ScriptsResearchRoute = ScriptsResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ScriptsRoute,
} as any)
const ScriptsManualRoute = ScriptsManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => ScriptsRoute,
} as any)
const ScriptsNumRoute = ScriptsNumRouteImport.update({
  id: '/$num',
  path: '/$num',
  getParentRoute: () => ScriptsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookSlugRoute = PlaybookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaybookRoute,
} as any)
const KpisPaRoute = KpisPaRouteImport.update({
  id: '/kpis/pa',
  path: '/kpis/pa',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisOwnerRoute = KpisOwnerRouteImport.update({
  id: '/kpis/owner',
  path: '/kpis/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisCfoRoute = KpisCfoRouteImport.update({
  id: '/kpis/cfo',
  path: '/kpis/cfo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const ApiStudioChatRoute = ApiStudioChatRouteImport.update({
  id: '/api/studio-chat',
  path: '/api/studio-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPalsRoute = ApiPalsRouteImport.update({
  id: '/api/pals',
  path: '/api/pals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/brand': typeof BrandRoute
  '/clients': typeof ClientsRouteWithChildren
  '/content': typeof ContentRoute
  '/finance': typeof FinanceRoute
  '/gear': typeof GearRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/productions': typeof ProductionsRoute
  '/schedule': typeof ScheduleRoute
  '/scoreboard': typeof ScoreboardRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/pals': typeof ApiPalsRoute
  '/api/studio-chat': typeof ApiStudioChatRoute
  '/clients/$id': typeof ClientsIdRoute
  '/kpis/cfo': typeof KpisCfoRoute
  '/kpis/owner': typeof KpisOwnerRoute
  '/kpis/pa': typeof KpisPaRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/scripts/$num': typeof ScriptsNumRoute
  '/scripts/manual': typeof ScriptsManualRoute
  '/scripts/research': typeof ScriptsResearchRoute
  '/scripts/strategy': typeof ScriptsStrategyRoute
  '/scripts/yourboy': typeof ScriptsYourboyRoute
  '/shoots/$id': typeof ShootsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/brand': typeof BrandRoute
  '/clients': typeof ClientsRouteWithChildren
  '/content': typeof ContentRoute
  '/finance': typeof FinanceRoute
  '/gear': typeof GearRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/productions': typeof ProductionsRoute
  '/schedule': typeof ScheduleRoute
  '/scoreboard': typeof ScoreboardRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/pals': typeof ApiPalsRoute
  '/api/studio-chat': typeof ApiStudioChatRoute
  '/clients/$id': typeof ClientsIdRoute
  '/kpis/cfo': typeof KpisCfoRoute
  '/kpis/owner': typeof KpisOwnerRoute
  '/kpis/pa': typeof KpisPaRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/scripts/$num': typeof ScriptsNumRoute
  '/scripts/manual': typeof ScriptsManualRoute
  '/scripts/research': typeof ScriptsResearchRoute
  '/scripts/strategy': typeof ScriptsStrategyRoute
  '/scripts/yourboy': typeof ScriptsYourboyRoute
  '/shoots/$id': typeof ShootsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/brand': typeof BrandRoute
  '/clients': typeof ClientsRouteWithChildren
  '/content': typeof ContentRoute
  '/finance': typeof FinanceRoute
  '/gear': typeof GearRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/productions': typeof ProductionsRoute
  '/schedule': typeof ScheduleRoute
  '/scoreboard': typeof ScoreboardRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/pals': typeof ApiPalsRoute
  '/api/studio-chat': typeof ApiStudioChatRoute
  '/clients/$id': typeof ClientsIdRoute
  '/kpis/cfo': typeof KpisCfoRoute
  '/kpis/owner': typeof KpisOwnerRoute
  '/kpis/pa': typeof KpisPaRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/scripts/$num': typeof ScriptsNumRoute
  '/scripts/manual': typeof ScriptsManualRoute
  '/scripts/research': typeof ScriptsResearchRoute
  '/scripts/strategy': typeof ScriptsStrategyRoute
  '/scripts/yourboy': typeof ScriptsYourboyRoute
  '/shoots/$id': typeof ShootsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assets'
    | '/brand'
    | '/clients'
    | '/content'
    | '/finance'
    | '/gear'
    | '/playbook'
    | '/productions'
    | '/schedule'
    | '/scoreboard'
    | '/scripts'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/admin/templates'
    | '/api/pals'
    | '/api/studio-chat'
    | '/clients/$id'
    | '/kpis/cfo'
    | '/kpis/owner'
    | '/kpis/pa'
    | '/playbook/$slug'
    | '/projects/$id'
    | '/scripts/$num'
    | '/scripts/manual'
    | '/scripts/research'
    | '/scripts/strategy'
    | '/scripts/yourboy'
    | '/shoots/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assets'
    | '/brand'
    | '/clients'
    | '/content'
    | '/finance'
    | '/gear'
    | '/playbook'
    | '/productions'
    | '/schedule'
    | '/scoreboard'
    | '/scripts'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/admin/templates'
    | '/api/pals'
    | '/api/studio-chat'
    | '/clients/$id'
    | '/kpis/cfo'
    | '/kpis/owner'
    | '/kpis/pa'
    | '/playbook/$slug'
    | '/projects/$id'
    | '/scripts/$num'
    | '/scripts/manual'
    | '/scripts/research'
    | '/scripts/strategy'
    | '/scripts/yourboy'
    | '/shoots/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assets'
    | '/brand'
    | '/clients'
    | '/content'
    | '/finance'
    | '/gear'
    | '/playbook'
    | '/productions'
    | '/schedule'
    | '/scoreboard'
    | '/scripts'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/admin/templates'
    | '/api/pals'
    | '/api/studio-chat'
    | '/clients/$id'
    | '/kpis/cfo'
    | '/kpis/owner'
    | '/kpis/pa'
    | '/playbook/$slug'
    | '/projects/$id'
    | '/scripts/$num'
    | '/scripts/manual'
    | '/scripts/research'
    | '/scripts/strategy'
    | '/scripts/yourboy'
    | '/shoots/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssetsRoute: typeof AssetsRoute
  BrandRoute: typeof BrandRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  ContentRoute: typeof ContentRoute
  FinanceRoute: typeof FinanceRoute
  GearRoute: typeof GearRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  ProductionsRoute: typeof ProductionsRoute
  ScheduleRoute: typeof ScheduleRoute
  ScoreboardRoute: typeof ScoreboardRoute
  ScriptsRoute: typeof ScriptsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  ApiPalsRoute: typeof ApiPalsRoute
  ApiStudioChatRoute: typeof ApiStudioChatRoute
  KpisCfoRoute: typeof KpisCfoRoute
  KpisOwnerRoute: typeof KpisOwnerRoute
  KpisPaRoute: typeof KpisPaRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ShootsIdRoute: typeof ShootsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions': {
      id: '/productions'
      path: '/productions'
      fullPath: '/productions'
      preLoaderRoute: typeof ProductionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoots/$id': {
      id: '/shoots/$id'
      path: '/shoots/$id'
      fullPath: '/shoots/$id'
      preLoaderRoute: typeof ShootsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/yourboy': {
      id: '/scripts/yourboy'
      path: '/yourboy'
      fullPath: '/scripts/yourboy'
      preLoaderRoute: typeof ScriptsYourboyRouteImport
      parentRoute: typeof ScriptsRoute
    }
    '/scripts/strategy': {
      id: '/scripts/strategy'
      path: '/strategy'
      fullPath: '/scripts/strategy'
      preLoaderRoute: typeof ScriptsStrategyRouteImport
      parentRoute: typeof ScriptsRoute
    }
    '/scripts/research': {
      id: '/scripts/research'
      path: '/research'
      fullPath: '/scripts/research'
      preLoaderRoute: typeof ScriptsResearchRouteImport
      parentRoute: typeof ScriptsRoute
    }
    '/scripts/manual': {
      id: '/scripts/manual'
      path: '/manual'
      fullPath: '/scripts/manual'
      preLoaderRoute: typeof ScriptsManualRouteImport
      parentRoute: typeof ScriptsRoute
    }
    '/scripts/$num': {
      id: '/scripts/$num'
      path: '/$num'
      fullPath: '/scripts/$num'
      preLoaderRoute: typeof ScriptsNumRouteImport
      parentRoute: typeof ScriptsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/$slug': {
      id: '/playbook/$slug'
      path: '/$slug'
      fullPath: '/playbook/$slug'
      preLoaderRoute: typeof PlaybookSlugRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/kpis/pa': {
      id: '/kpis/pa'
      path: '/kpis/pa'
      fullPath: '/kpis/pa'
      preLoaderRoute: typeof KpisPaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis/owner': {
      id: '/kpis/owner'
      path: '/kpis/owner'
      fullPath: '/kpis/owner'
      preLoaderRoute: typeof KpisOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis/cfo': {
      id: '/kpis/cfo'
      path: '/kpis/cfo'
      fullPath: '/kpis/cfo'
      preLoaderRoute: typeof KpisCfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/api/studio-chat': {
      id: '/api/studio-chat'
      path: '/api/studio-chat'
      fullPath: '/api/studio-chat'
      preLoaderRoute: typeof ApiStudioChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pals': {
      id: '/api/pals'
      path: '/api/pals'
      fullPath: '/api/pals'
      preLoaderRoute: typeof ApiPalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface PlaybookRouteChildren {
  PlaybookSlugRoute: typeof PlaybookSlugRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookSlugRoute: PlaybookSlugRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

interface ScriptsRouteChildren {
  ScriptsNumRoute: typeof ScriptsNumRoute
  ScriptsManualRoute: typeof ScriptsManualRoute
  ScriptsResearchRoute: typeof ScriptsResearchRoute
  ScriptsStrategyRoute: typeof ScriptsStrategyRoute
  ScriptsYourboyRoute: typeof ScriptsYourboyRoute
}

const ScriptsRouteChildren: ScriptsRouteChildren = {
  ScriptsNumRoute: ScriptsNumRoute,
  ScriptsManualRoute: ScriptsManualRoute,
  ScriptsResearchRoute: ScriptsResearchRoute,
  ScriptsStrategyRoute: ScriptsStrategyRoute,
  ScriptsYourboyRoute: ScriptsYourboyRoute,
}

const ScriptsRouteWithChildren =
  ScriptsRoute._addFileChildren(ScriptsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssetsRoute: AssetsRoute,
  BrandRoute: BrandRoute,
  ClientsRoute: ClientsRouteWithChildren,
  ContentRoute: ContentRoute,
  FinanceRoute: FinanceRoute,
  GearRoute: GearRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  ProductionsRoute: ProductionsRoute,
  ScheduleRoute: ScheduleRoute,
  ScoreboardRoute: ScoreboardRoute,
  ScriptsRoute: ScriptsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  ApiPalsRoute: ApiPalsRoute,
  ApiStudioChatRoute: ApiStudioChatRoute,
  KpisCfoRoute: KpisCfoRoute,
  KpisOwnerRoute: KpisOwnerRoute,
  KpisPaRoute: KpisPaRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ShootsIdRoute: ShootsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
